name: Django-app workflow

on: push

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          source venv/bin/activate
          echo "TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}" >> .env
  build-and-push:
    name: Push Docker image
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Yandex Cloud
        uses: yandex-cloud/github-actions/login@v0.2.0
        with:
          yc_token: ${{ secrets.YC_TOKEN }}
      - name: Build Docker Image
        run: |
          docker build -t cr.yandex/crpt5n1ucdvd5ncc3n63/Django-test .
      - name: Push Docker Image
        run: |
          docker push docker build -t cr.yandex/crpt5n1ucdvd5ncc3n63/Django-test .
